### PR TITLE
fixed key errors in _process_connectivity_file

### PR DESCRIPTION
**Pull request by AleksVAnd**
When I used it first, it was throwing the following errors:
```
  File "src/netpol_synth.py", line 72, in _process_connectivity_file
    src_deploy = self._find_or_add_deployment(connection['source']['Resource'])
KeyError: 'source'
```

I checked the connection file generated by the topology analyzer - it doesn't have a key named "source". So, I changed this to "link". It kept throwing error for "Resource". The topology file has keys with small letter "resource". 

Finally, it was working as expected.
Signed-off-by: Aleksandar Andonov <aleksv.andonov@protonmail.com>

### CODE REVIEW

**Comment by zivnevo** [comment]
Thanks for this PR 👍 
It indeed seems as if the output of `cluster-topology-analyzer` has changed recently, and this breaks the synthesizer.
Note that `cluster-topology-analyzer` now has an independent synthesis feature (but only K8s, no baseline rules).

For this PR to be merged, the connectivity JSON files in `tests/connectivity_jsons` also have to be modified accordingly.

**Comment by AleksVAnd** [comment]
> 

Ah, yes - that's nice. Thanks for letting me know about the analyser. I am going to find a simple application to extract a connection file and include in the tests.

**Comment by AleksVAnd** [comment]
The test_push.yaml > run_all_tests.py includes the previous YAML files and fails. I guess I should remove them.

**Comment by zivnevo** [comment]
@AleksVAnd, the connectivity JSON files should be modified, not deleted. Please let us know if you need our help in doing that.

**Comment by AleksVAnd** [comment]
> @AleksVAnd, the connectivity JSON files should be modified, not deleted. Please let us know if you need our help in doing that.

Yes, please.

**Review by zivnevo — APPROVED** [review]

**Pull request merged**
